### PR TITLE
o and q commands

### PR DESCRIPTION
**Pull request by pmcelhaney**
This change adds an option to open a browser after the server is started by pressing `o`. It also adds a `q` option to shut down the server.  

```sh
* Static server successfully started.
* Serving files at: http://localhost:9080
* Press Ctrl+C or q to shutdown.
* Press o to open in a browser.
```

### CODE REVIEW

**Comment by mathiasrw** [comment]
I quite like this - and I just realised I made a PR that uses the -q flag - that might be a bit confusing. Ill change to -s flag so it still makes sense.

**Comment by mathiasrw** [comment]
I have changed PR #45 to use -s flag instead (even if it technically did not collided)

**Comment by mathiasrw** [comment]
I have made a [PR to this PR](https://github.com/pmcelhaney/static-server/pull/1) that changes the wording a bit and handles both upper and lower case. 

With the suggest PR the output will be:

```

* Static server successfully started
* Serving files at: http://localhost:9080
* Press o to open in a browser
* Press q to exit
```

**Comment by pmcelhaney** [comment]
Thank @mathiasrw! I've merged your edits into my PR. I'm okay with using "x" to exit.

**Pull request closed without merging**
