### PR TITLE
 Add option for quiet output

### PR DESCRIPTION
**Pull request by mathiasrw**
This PR will add the option to set the `--quiet` flag leading to information about each request not being displayed. 

I have been a bit lazy and also bundles the following into the same PR:  
- fix 2 misleading error messages 
- Fix 2 vulnerabilities in the dependency graph
- It now provides a helpful error message when the port is already in use. 

Let me know if you prefer a separate PR for each aspect.

---
This change is [Reviewable](https://reviewable.io/reviews/nbluis/static-server/45)

### CODE REVIEW

**Comment by yanickrochon** [comment]
I still do not understand the `delete program.index` in this PR, and how is it related to the option (or even necessary)?

**Comment by mathiasrw** [comment]
Good question. Actually, it is not directly related to the headline of the PR and I would be willing to provide a separate PR for each issue addressed. 

Any command from the CLI was giving me this as the first part of the output:
`options.index is now deprecated please use options.templates.index instead.`

The message came from https://github.com/nbluis/static-server/blob/bf75abdd8142f8378ae22b4fb11677b11d2c1534/server.js#L88 - because options.index was set by the commander module while also setting the correct template variable with https://github.com/nbluis/static-server/blob/bf75abdd8142f8378ae22b4fb11677b11d2c1534/bin/static-server.js#L142. 

I have a feeling that it could be a changed behavour in the commander module. Anyway: this is just to remove the warning so people dont get confused. Inputs and comments on the solution much aprecheated.

**Comment by yanickrochon** [comment]
I see. Thank you for explaining. Could you document this so we know when to remove this in the future?

**Comment by mathiasrw** [comment]
Hi @yanickrochon Sure I can. Where would you like me to document it?

**Comment by yanickrochon** [comment]
@mathiasrw just for posterity's sake :stuck_out_tongue:

**Comment by nbluis** [comment]
Hello guys.

I've been distant these days but I'm back. Sorry. 😃 

Many thanks for the help @mathiasrw and @yanickrochon, your contribution was great.

I have only one concern.
Make sense to have the function `cmdSetPort` that is notoriously complex just to have this log in exceptional cases?

```
console.log (chalk.blue ('*'), 'You could try the next port using:', chalk.green.bold (cmdSetPort (1 + parseInt (program.port))));
```

What do you think ?

**Comment by mathiasrw** [comment]
Let me know if you would like me to change it.

**Comment by nbluis** [comment]
I think we can change it.

Really thanks for your help @mathiasrw.

**Comment by foxdonut** [comment]
@mathiasrw thanks for spotting the issue with `options.index is now deprecated please use options.templates.index instead`, it confused me and my users as well.

@nbluis thank you for `static-server`, I use it for [Meiosis examples](http://meiosis.js.org/examples.html), works great!

**Comment by nbluis** [comment]
Hi guys, thanks a lot for your help.

I decided to retire the project as I no longer have the time to maintain it.

If any of you are interested in making a fork, I'd be happy to mention it for others in the community to use.

More information about this in the README.

**Pull request closed without merging**
